backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/uploads" 
public_folder: "uploads"
display_url: https://worldofsteelcraft.tk
logo_url: /images/logo.png

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Custom Preview Image", name: "customPagePreviewImageURL", widget: "image", required: false}

      - {label: "Comments", name: "enableComments", widget: "boolean", default: false }
      - {label: "Exclude from Sitemap", name: "sitemapExclude", widget: "boolean", required: false}
      - {label: "Blog Author", name: "author", widget: "string", required: true}
  - name: "season-download" # Used in routes, e.g., /admin/collections/blog
    label: "Season Download" # Used in the UI
    folder: "content/season-download" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Custom Preview Image", name: "customPagePreviewImageURL", widget: "image", required: false, default: "/images/preview-seasondl.jpg"}
      - {label: "Comments", name: "enableComments", widget: "boolean", default: false, required: false}
      - {label: "Exclude from Sitemap", name: "sitemapExclude", widget: "boolean", required: false}
  - name: "ban" # Used in routes, e.g., /admin/collections/blog
    label: "Ban" # Used in the UI
    folder: "content/ban" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Custom Preview Image", name: "customPagePreviewImageURL", widget: "image", required: false, default: "/images/preview-banhammer.png"}
      - {label: "Exclude from Sitemap", name: "sitemapExclude", widget: "boolean", required: false}
      - {label: "Blog Author", name: "author", widget: "string", required: true}
  - name: "rules" # Used in routes, e.g., /admin/collections/blog
    label: "Rules" # Used in the UI
    folder: "content/rules" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Comments", name: "enableComments", widget: "boolean", default: false }
      - {label: "Exclude from Sitemap", name: "sitemapExclude", widget: "boolean", required: false}
  - name: "Knowledgebase" # Used in routes, e.g., /admin/collections/blog
    label: "Knowledgebase" # Used in the UI
    folder: "content/knowledgebase" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Custom Preview Image", name: "customPagePreviewImageURL", widget: "image", required: false, default: "/images/preview-knowledgebase.png"}
      - {label: "Comments", name: "enableComments", widget: "boolean", default: false }
      - {label: "Exclude from Sitemap", name: "sitemapExclude", widget: "boolean", required: false}
  - name: "donation-log" # Used in routes, e.g., /admin/collections/blog
    label: "Donation Log(Closed, WIP)" # Used in the UI
    folder: "content/donation-log" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Custom Preview Image", name: "customPagePreviewImageURL", widget: "image", required: false, default: "/images/preview-donationlog.png"}
      - {label: "Comments", name: "enableComments", widget: "boolean", default: false }
      - {label: "Exclude from Sitemap", name: "sitemapExclude", widget: "boolean", required: false}
      - {label: "Blog Author", name: "author", widget: "string", required: true}
